package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name="article"
    ,catalog="aaetp"
)
public class Article  implements java.io.Serializable {


     private Integer idArticle;
     private int marqueIdMarque;
     private String nom;
     private String reference;
     private float prix;
     private String description;
     private String discriminator;

    public Article() {
    }

	
    public Article(int marqueIdMarque, float prix, String discriminator) {
        this.marqueIdMarque = marqueIdMarque;
        this.prix = prix;
        this.discriminator = discriminator;
    }
    public Article(int marqueIdMarque, String nom, String reference, float prix, String description, String discriminator) {
       this.marqueIdMarque = marqueIdMarque;
       this.nom = nom;
       this.reference = reference;
       this.prix = prix;
       this.description = description;
       this.discriminator = discriminator;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdArticle", unique=true, nullable=false)
    public Integer getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Integer idArticle) {
        this.idArticle = idArticle;
    }

    
    @Column(name="MarqueIdMarque", nullable=false)
    public int getMarqueIdMarque() {
        return this.marqueIdMarque;
    }
    
    public void setMarqueIdMarque(int marqueIdMarque) {
        this.marqueIdMarque = marqueIdMarque;
    }

    
    @Column(name="Nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="Reference")
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="Prix", nullable=false, precision=12, scale=0)
    public float getPrix() {
        return this.prix;
    }
    
    public void setPrix(float prix) {
        this.prix = prix;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Discriminator", nullable=false)
    public String getDiscriminator() {
        return this.discriminator;
    }
    
    public void setDiscriminator(String discriminator) {
        this.discriminator = discriminator;
    }




}


