package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie"
    ,catalog="aaetp"
)
public class Categorie  implements java.io.Serializable {


     private Integer idCategorie;
     private String nom;
     private Set souscategories = new HashSet(0);

    public Categorie() {
    }

    public Categorie(String nom, Set souscategories) {
       this.nom = nom;
       this.souscategories = souscategories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCategorie", unique=true, nullable=false)
    public Integer getIdCategorie() {
        return this.idCategorie;
    }
    
    public void setIdCategorie(Integer idCategorie) {
        this.idCategorie = idCategorie;
    }

    
    @Column(name="Nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="souscategorie_categorie", catalog="aaetp", joinColumns = { 
        @JoinColumn(name="CategorieIdCategorie", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="SousCategorieIdSousCategorie", nullable=false, updatable=false) })
    public Set getSouscategories() {
        return this.souscategories;
    }
    
    public void setSouscategories(Set souscategories) {
        this.souscategories = souscategories;
    }




}


