package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name="categorie"
    ,catalog="aaetp"
)
public class Categorie  implements java.io.Serializable {


     private Integer idCategorie;
     private String nom;

    public Categorie() {
    }

    public Categorie(String nom) {
       this.nom = nom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCategorie", unique=true, nullable=false)
    public Integer getIdCategorie() {
        return this.idCategorie;
    }
    
    public void setIdCategorie(Integer idCategorie) {
        this.idCategorie = idCategorie;
    }

    
    @Column(name="Nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


