package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name="commande"
    ,catalog="aaetp"
)
public class Commande  implements java.io.Serializable {


     private Integer idCommande;
     private int employeIdPersonne;

    public Commande() {
    }

    public Commande(int employeIdPersonne) {
       this.employeIdPersonne = employeIdPersonne;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCommande", unique=true, nullable=false)
    public Integer getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(Integer idCommande) {
        this.idCommande = idCommande;
    }

    
    @Column(name="EmployeIdPersonne", nullable=false)
    public int getEmployeIdPersonne() {
        return this.employeIdPersonne;
    }
    
    public void setEmployeIdPersonne(int employeIdPersonne) {
        this.employeIdPersonne = employeIdPersonne;
    }




}


