package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emplacement generated by hbm2java
 */
@Entity
@Table(name="emplacement"
    ,catalog="aaetp"
)
public class Emplacement  implements java.io.Serializable {


     private Integer idEmplacement;
     private Stock stock;
     private String allee;
     private String rangee;
     private String etage;

    public Emplacement() {
    }

	
    public Emplacement(Stock stock) {
        this.stock = stock;
    }
    public Emplacement(Stock stock, String allee, String rangee, String etage) {
       this.stock = stock;
       this.allee = allee;
       this.rangee = rangee;
       this.etage = etage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdEmplacement", unique=true, nullable=false)
    public Integer getIdEmplacement() {
        return this.idEmplacement;
    }
    
    public void setIdEmplacement(Integer idEmplacement) {
        this.idEmplacement = idEmplacement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StockIdStock", nullable=false)
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }

    
    @Column(name="Allee")
    public String getAllee() {
        return this.allee;
    }
    
    public void setAllee(String allee) {
        this.allee = allee;
    }

    
    @Column(name="Rangee")
    public String getRangee() {
        return this.rangee;
    }
    
    public void setRangee(String rangee) {
        this.rangee = rangee;
    }

    
    @Column(name="Etage")
    public String getEtage() {
        return this.etage;
    }
    
    public void setEtage(String etage) {
        this.etage = etage;
    }




}


