package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employe generated by hbm2java
 */
@Entity
@Table(name="employe"
    ,catalog="aaetp"
)
public class Employe  implements java.io.Serializable {


     private Integer idPersonne;
     private String adresse;
     private String password;
     private boolean isAdmin;
     private String nom;
     private String prenom;
     private String telephone;
     private String mail;
     private Set commandes = new HashSet(0);

    public Employe() {
    }

	
    public Employe(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Employe(String adresse, String password, boolean isAdmin, String nom, String prenom, String telephone, String mail, Set commandes) {
       this.adresse = adresse;
       this.password = password;
       this.isAdmin = isAdmin;
       this.nom = nom;
       this.prenom = prenom;
       this.telephone = telephone;
       this.mail = mail;
       this.commandes = commandes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdPersonne", unique=true, nullable=false)
    public Integer getIdPersonne() {
        return this.idPersonne;
    }
    
    public void setIdPersonne(Integer idPersonne) {
        this.idPersonne = idPersonne;
    }

    
    @Column(name="Adresse")
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="Password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="IsAdmin", nullable=false)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    
    @Column(name="Nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="Prenom")
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="Telephone")
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="Mail")
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employe")
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


