package ca.uqac.archi.model;
// Generated 24 févr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name="facture"
    ,catalog="aaetp"
)
public class Facture  implements java.io.Serializable {


     private Integer idFacture;
     private int fournisseurIdFournisseur;
     private int commandeIdCommande;
     private String descriptif;
     private float prixFacture;

    public Facture() {
    }

	
    public Facture(int fournisseurIdFournisseur, int commandeIdCommande, float prixFacture) {
        this.fournisseurIdFournisseur = fournisseurIdFournisseur;
        this.commandeIdCommande = commandeIdCommande;
        this.prixFacture = prixFacture;
    }
    public Facture(int fournisseurIdFournisseur, int commandeIdCommande, String descriptif, float prixFacture) {
       this.fournisseurIdFournisseur = fournisseurIdFournisseur;
       this.commandeIdCommande = commandeIdCommande;
       this.descriptif = descriptif;
       this.prixFacture = prixFacture;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdFacture", unique=true, nullable=false)
    public Integer getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(Integer idFacture) {
        this.idFacture = idFacture;
    }

    
    @Column(name="FournisseurIdFournisseur", nullable=false)
    public int getFournisseurIdFournisseur() {
        return this.fournisseurIdFournisseur;
    }
    
    public void setFournisseurIdFournisseur(int fournisseurIdFournisseur) {
        this.fournisseurIdFournisseur = fournisseurIdFournisseur;
    }

    
    @Column(name="CommandeIdCommande", nullable=false)
    public int getCommandeIdCommande() {
        return this.commandeIdCommande;
    }
    
    public void setCommandeIdCommande(int commandeIdCommande) {
        this.commandeIdCommande = commandeIdCommande;
    }

    
    @Column(name="Descriptif")
    public String getDescriptif() {
        return this.descriptif;
    }
    
    public void setDescriptif(String descriptif) {
        this.descriptif = descriptif;
    }

    
    @Column(name="PrixFacture", nullable=false, precision=12, scale=0)
    public float getPrixFacture() {
        return this.prixFacture;
    }
    
    public void setPrixFacture(float prixFacture) {
        this.prixFacture = prixFacture;
    }




}


