package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name="facture"
    ,catalog="aaetp"
)
public class Facture  implements java.io.Serializable {


     private Integer idFacture;
     private Commande commande;
     private Fournisseur fournisseur;
     private String descriptif;
     private float prixFacture;

    public Facture() {
    }

	
    public Facture(Commande commande, Fournisseur fournisseur, float prixFacture) {
        this.commande = commande;
        this.fournisseur = fournisseur;
        this.prixFacture = prixFacture;
    }
    public Facture(Commande commande, Fournisseur fournisseur, String descriptif, float prixFacture) {
       this.commande = commande;
       this.fournisseur = fournisseur;
       this.descriptif = descriptif;
       this.prixFacture = prixFacture;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdFacture", unique=true, nullable=false)
    public Integer getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(Integer idFacture) {
        this.idFacture = idFacture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CommandeIdCommande", nullable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FournisseurIdFournisseur", nullable=false)
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }

    
    @Column(name="Descriptif")
    public String getDescriptif() {
        return this.descriptif;
    }
    
    public void setDescriptif(String descriptif) {
        this.descriptif = descriptif;
    }

    
    @Column(name="PrixFacture", nullable=false, precision=12, scale=0)
    public float getPrixFacture() {
        return this.prixFacture;
    }
    
    public void setPrixFacture(float prixFacture) {
        this.prixFacture = prixFacture;
    }




}


