package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name="fournisseur"
    ,catalog="aaetp"
)
public class Fournisseur  implements java.io.Serializable {


     private Integer idFournisseur;
     private String adresse;
     private String nom;
     private String raisonSociale;
     private String prenom;
     private String telephone;
     private String mail;
     private Set factures = new HashSet(0);

    public Fournisseur() {
    }

    public Fournisseur(String adresse, String nom, String raisonSociale, String prenom, String telephone, String mail, Set factures) {
       this.adresse = adresse;
       this.nom = nom;
       this.raisonSociale = raisonSociale;
       this.prenom = prenom;
       this.telephone = telephone;
       this.mail = mail;
       this.factures = factures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdFournisseur", unique=true, nullable=false)
    public Integer getIdFournisseur() {
        return this.idFournisseur;
    }
    
    public void setIdFournisseur(Integer idFournisseur) {
        this.idFournisseur = idFournisseur;
    }

    
    @Column(name="Adresse")
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="Nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="RaisonSociale")
    public String getRaisonSociale() {
        return this.raisonSociale;
    }
    
    public void setRaisonSociale(String raisonSociale) {
        this.raisonSociale = raisonSociale;
    }

    
    @Column(name="Prenom")
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="Telephone")
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="Mail")
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fournisseur")
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }




}


