package ca.uqac.archi.model;
// Generated 24 févr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lignecommande generated by hbm2java
 */
@Entity
@Table(name="lignecommande"
    ,catalog="aaetp"
)
public class Lignecommande  implements java.io.Serializable {


     private Integer idLigneCommande;
     private int articleIdArticle;
     private int commandeIdCommande;
     private int quantite;

    public Lignecommande() {
    }

    public Lignecommande(int articleIdArticle, int commandeIdCommande, int quantite) {
       this.articleIdArticle = articleIdArticle;
       this.commandeIdCommande = commandeIdCommande;
       this.quantite = quantite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdLigneCommande", unique=true, nullable=false)
    public Integer getIdLigneCommande() {
        return this.idLigneCommande;
    }
    
    public void setIdLigneCommande(Integer idLigneCommande) {
        this.idLigneCommande = idLigneCommande;
    }

    
    @Column(name="ArticleIdArticle", nullable=false)
    public int getArticleIdArticle() {
        return this.articleIdArticle;
    }
    
    public void setArticleIdArticle(int articleIdArticle) {
        this.articleIdArticle = articleIdArticle;
    }

    
    @Column(name="CommandeIdCommande", nullable=false)
    public int getCommandeIdCommande() {
        return this.commandeIdCommande;
    }
    
    public void setCommandeIdCommande(int commandeIdCommande) {
        this.commandeIdCommande = commandeIdCommande;
    }

    
    @Column(name="Quantite", nullable=false)
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }




}


