package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Livraison generated by hbm2java
 */
@Entity
@Table(name="livraison"
    ,catalog="aaetp"
)
public class Livraison  implements java.io.Serializable {


     private Integer idLivraison;
     private int commandeIdCommande;
     private Date date;

    public Livraison() {
    }

	
    public Livraison(int commandeIdCommande) {
        this.commandeIdCommande = commandeIdCommande;
    }
    public Livraison(int commandeIdCommande, Date date) {
       this.commandeIdCommande = commandeIdCommande;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdLivraison", unique=true, nullable=false)
    public Integer getIdLivraison() {
        return this.idLivraison;
    }
    
    public void setIdLivraison(Integer idLivraison) {
        this.idLivraison = idLivraison;
    }

    
    @Column(name="CommandeIdCommande", nullable=false)
    public int getCommandeIdCommande() {
        return this.commandeIdCommande;
    }
    
    public void setCommandeIdCommande(int commandeIdCommande) {
        this.commandeIdCommande = commandeIdCommande;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


