package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Livraison generated by hbm2java
 */
@Entity
@Table(name="livraison"
    ,catalog="aaetp"
)
public class Livraison  implements java.io.Serializable {


     private Integer idLivraison;
     private Commande commande;
     private Date date;

    public Livraison() {
    }

	
    public Livraison(Commande commande) {
        this.commande = commande;
    }
    public Livraison(Commande commande, Date date) {
       this.commande = commande;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdLivraison", unique=true, nullable=false)
    public Integer getIdLivraison() {
        return this.idLivraison;
    }
    
    public void setIdLivraison(Integer idLivraison) {
        this.idLivraison = idLivraison;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CommandeIdCommande", nullable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


