package ca.uqac.archi.model;
// Generated 24 févr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Marque generated by hbm2java
 */
@Entity
@Table(name="marque"
    ,catalog="aaetp"
)
public class Marque  implements java.io.Serializable {


     private Integer idMarque;
     private String libelleMarque;

    public Marque() {
    }

    public Marque(String libelleMarque) {
       this.libelleMarque = libelleMarque;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdMarque", unique=true, nullable=false)
    public Integer getIdMarque() {
        return this.idMarque;
    }
    
    public void setIdMarque(Integer idMarque) {
        this.idMarque = idMarque;
    }

    
    @Column(name="LibelleMarque")
    public String getLibelleMarque() {
        return this.libelleMarque;
    }
    
    public void setLibelleMarque(String libelleMarque) {
        this.libelleMarque = libelleMarque;
    }




}


