package ca.uqac.archi.model;
// Generated 24 févr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SouscategorieCategorie generated by hbm2java
 */
@Entity
@Table(name="souscategorie_categorie"
    ,catalog="aaetp"
)
public class SouscategorieCategorie  implements java.io.Serializable {


     private SouscategorieCategorieId id;

    public SouscategorieCategorie() {
    }

    public SouscategorieCategorie(SouscategorieCategorieId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sousCategorieIdSousCategorie", column=@Column(name="SousCategorieIdSousCategorie", nullable=false) ), 
        @AttributeOverride(name="categorieIdCategorie", column=@Column(name="CategorieIdCategorie", nullable=false) ) } )
    public SouscategorieCategorieId getId() {
        return this.id;
    }
    
    public void setId(SouscategorieCategorieId id) {
        this.id = id;
    }




}


