package ca.uqac.archi.model;
// Generated 24 févr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SouscategorieCategorieId generated by hbm2java
 */
@Embeddable
public class SouscategorieCategorieId  implements java.io.Serializable {


     private int sousCategorieIdSousCategorie;
     private int categorieIdCategorie;

    public SouscategorieCategorieId() {
    }

    public SouscategorieCategorieId(int sousCategorieIdSousCategorie, int categorieIdCategorie) {
       this.sousCategorieIdSousCategorie = sousCategorieIdSousCategorie;
       this.categorieIdCategorie = categorieIdCategorie;
    }
   


    @Column(name="SousCategorieIdSousCategorie", nullable=false)
    public int getSousCategorieIdSousCategorie() {
        return this.sousCategorieIdSousCategorie;
    }
    
    public void setSousCategorieIdSousCategorie(int sousCategorieIdSousCategorie) {
        this.sousCategorieIdSousCategorie = sousCategorieIdSousCategorie;
    }


    @Column(name="CategorieIdCategorie", nullable=false)
    public int getCategorieIdCategorie() {
        return this.categorieIdCategorie;
    }
    
    public void setCategorieIdCategorie(int categorieIdCategorie) {
        this.categorieIdCategorie = categorieIdCategorie;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SouscategorieCategorieId) ) return false;
		 SouscategorieCategorieId castOther = ( SouscategorieCategorieId ) other; 
         
		 return (this.getSousCategorieIdSousCategorie()==castOther.getSousCategorieIdSousCategorie())
 && (this.getCategorieIdCategorie()==castOther.getCategorieIdCategorie());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSousCategorieIdSousCategorie();
         result = 37 * result + this.getCategorieIdCategorie();
         return result;
   }   


}


