package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SouscategorieArticleId generated by hbm2java
 */
@Embeddable
public class SouscategorieArticleId  implements java.io.Serializable {


     private int sousCategorieIdSousCategorie;
     private int articleIdArticle;

    public SouscategorieArticleId() {
    }

    public SouscategorieArticleId(int sousCategorieIdSousCategorie, int articleIdArticle) {
       this.sousCategorieIdSousCategorie = sousCategorieIdSousCategorie;
       this.articleIdArticle = articleIdArticle;
    }
   


    @Column(name="SousCategorieIdSousCategorie", nullable=false)
    public int getSousCategorieIdSousCategorie() {
        return this.sousCategorieIdSousCategorie;
    }
    
    public void setSousCategorieIdSousCategorie(int sousCategorieIdSousCategorie) {
        this.sousCategorieIdSousCategorie = sousCategorieIdSousCategorie;
    }


    @Column(name="ArticleIdArticle", nullable=false)
    public int getArticleIdArticle() {
        return this.articleIdArticle;
    }
    
    public void setArticleIdArticle(int articleIdArticle) {
        this.articleIdArticle = articleIdArticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SouscategorieArticleId) ) return false;
		 SouscategorieArticleId castOther = ( SouscategorieArticleId ) other; 
         
		 return (this.getSousCategorieIdSousCategorie()==castOther.getSousCategorieIdSousCategorie())
 && (this.getArticleIdArticle()==castOther.getArticleIdArticle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSousCategorieIdSousCategorie();
         result = 37 * result + this.getArticleIdArticle();
         return result;
   }   


}


