package ca.uqac.archi.model;
// Generated 24 févr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Souscategorie generated by hbm2java
 */
@Entity
@Table(name="souscategorie"
    ,catalog="aaetp"
)
public class Souscategorie  implements java.io.Serializable {


     private Integer idSousCategorie;
     private String nom;

    public Souscategorie() {
    }

    public Souscategorie(String nom) {
       this.nom = nom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdSousCategorie", unique=true, nullable=false)
    public Integer getIdSousCategorie() {
        return this.idSousCategorie;
    }
    
    public void setIdSousCategorie(Integer idSousCategorie) {
        this.idSousCategorie = idSousCategorie;
    }

    
    @Column(name="Nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


