package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockArticleId generated by hbm2java
 */
@Embeddable
public class StockArticleId  implements java.io.Serializable {


     private int stockIdStock;
     private int articleIdArticle;

    public StockArticleId() {
    }

    public StockArticleId(int stockIdStock, int articleIdArticle) {
       this.stockIdStock = stockIdStock;
       this.articleIdArticle = articleIdArticle;
    }
   


    @Column(name="StockIdStock", nullable=false)
    public int getStockIdStock() {
        return this.stockIdStock;
    }
    
    public void setStockIdStock(int stockIdStock) {
        this.stockIdStock = stockIdStock;
    }


    @Column(name="ArticleIdArticle", nullable=false)
    public int getArticleIdArticle() {
        return this.articleIdArticle;
    }
    
    public void setArticleIdArticle(int articleIdArticle) {
        this.articleIdArticle = articleIdArticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockArticleId) ) return false;
		 StockArticleId castOther = ( StockArticleId ) other; 
         
		 return (this.getStockIdStock()==castOther.getStockIdStock())
 && (this.getArticleIdArticle()==castOther.getArticleIdArticle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStockIdStock();
         result = 37 * result + this.getArticleIdArticle();
         return result;
   }   


}


