package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StockArticle generated by hbm2java
 */
@Entity
@Table(name="stock_article"
    ,catalog="aaetp"
)
public class StockArticle  implements java.io.Serializable {


     private StockArticleId id;

    public StockArticle() {
    }

    public StockArticle(StockArticleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="stockIdStock", column=@Column(name="StockIdStock", nullable=false) ), 
        @AttributeOverride(name="articleIdArticle", column=@Column(name="ArticleIdArticle", nullable=false) ) } )
    public StockArticleId getId() {
        return this.id;
    }
    
    public void setId(StockArticleId id) {
        this.id = id;
    }




}


