package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name="vehicule"
    ,catalog="aaetp"
)
public class Vehicule  implements java.io.Serializable {


     private Integer idVehicule;
     private int marqueIdMarque;
     private int annee;
     private String libelleVehicule;

    public Vehicule() {
    }

	
    public Vehicule(int marqueIdMarque, int annee) {
        this.marqueIdMarque = marqueIdMarque;
        this.annee = annee;
    }
    public Vehicule(int marqueIdMarque, int annee, String libelleVehicule) {
       this.marqueIdMarque = marqueIdMarque;
       this.annee = annee;
       this.libelleVehicule = libelleVehicule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdVehicule", unique=true, nullable=false)
    public Integer getIdVehicule() {
        return this.idVehicule;
    }
    
    public void setIdVehicule(Integer idVehicule) {
        this.idVehicule = idVehicule;
    }

    
    @Column(name="MarqueIdMarque", nullable=false)
    public int getMarqueIdMarque() {
        return this.marqueIdMarque;
    }
    
    public void setMarqueIdMarque(int marqueIdMarque) {
        this.marqueIdMarque = marqueIdMarque;
    }

    
    @Column(name="Annee", nullable=false)
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }

    
    @Column(name="LibelleVehicule")
    public String getLibelleVehicule() {
        return this.libelleVehicule;
    }
    
    public void setLibelleVehicule(String libelleVehicule) {
        this.libelleVehicule = libelleVehicule;
    }




}


