package ca.uqac.archi.model;
// Generated 24 fevr. 2018 20:23:59 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VehiculeArticle generated by hbm2java
 */
@Entity
@Table(name="vehicule_article"
    ,catalog="aaetp"
)
public class VehiculeArticle  implements java.io.Serializable {


     private VehiculeArticleId id;

    public VehiculeArticle() {
    }

    public VehiculeArticle(VehiculeArticleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vehiculeIdVehicule", column=@Column(name="VehiculeIdVehicule", nullable=false) ), 
        @AttributeOverride(name="articleIdArticle", column=@Column(name="ArticleIdArticle", nullable=false) ) } )
    public VehiculeArticleId getId() {
        return this.id;
    }
    
    public void setId(VehiculeArticleId id) {
        this.id = id;
    }




}


