package ca.uqac.archi.model;
// Generated 1 mars 2018 16:36:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehicule generated by hbm2java
 */
@Entity
@Table(name="vehicule"
    ,catalog="aaetp"
)
public class Vehicule  implements java.io.Serializable {


     private Integer idVehicule;
     private Marque marque;
     private int annee;
     private String libelleVehicule;
     private Set articles = new HashSet(0);

    public Vehicule() {
    }

	
    public Vehicule(Marque marque, int annee) {
        this.marque = marque;
        this.annee = annee;
    }
    public Vehicule(Marque marque, int annee, String libelleVehicule, Set articles) {
       this.marque = marque;
       this.annee = annee;
       this.libelleVehicule = libelleVehicule;
       this.articles = articles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdVehicule", unique=true, nullable=false)
    public Integer getIdVehicule() {
        return this.idVehicule;
    }
    
    public void setIdVehicule(Integer idVehicule) {
        this.idVehicule = idVehicule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MarqueIdMarque", nullable=false)
    public Marque getMarque() {
        return this.marque;
    }
    
    public void setMarque(Marque marque) {
        this.marque = marque;
    }

    
    @Column(name="Annee", nullable=false)
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }

    
    @Column(name="LibelleVehicule")
    public String getLibelleVehicule() {
        return this.libelleVehicule;
    }
    
    public void setLibelleVehicule(String libelleVehicule) {
        this.libelleVehicule = libelleVehicule;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="vehicule_article", catalog="aaetp", joinColumns = { 
        @JoinColumn(name="VehiculeIdVehicule", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ArticleIdArticle", nullable=false, updatable=false) })
    public Set getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set articles) {
        this.articles = articles;
    }
}
